In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split
import math
from collections import Counter

When a decision Tree\
Classifies categories -> Classification Tree\
predicts numerical values -> Regression Tree

1. Root/Root Node
2. Internal Nodes/Branches
3. Leaf Node/Leafs

Impure leaves if quantification is mixed
At each node we want to find out the best split value, best split treshhold

**Gini Impurity/ Entropy Gain/ Information Gain**

IG = E(P) - [Weighted Avg] . E(Children)

stopping criteria: max depth, min node samples, no more class distribution

In [2]:
data = datasets.load_breast_cancer()
X, y = data.data, data.target
X, y = datasets.make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [3]:
def printAll(*ps) : 
    [print(p) for p in ps]

In [164]:
printAll(
np.bincount([0,1,1]),
Counter([0,1,1]).most_common(),
)

[1 2]
[(1, 2), (0, 1)]
[[0]
 [1]
 [4]
 [5]]


In [30]:
printAll(
np.bincount(y_test),
np.bincount(y_test)/len(y_test)
)

[152 178]
[0.46060606 0.53939394]


In [135]:
np.random.choice(10 ,3)
np.random.choice(10 ,3)

array([8, 5, 7])

In [167]:
printAll(
    np.argwhere(np.array([0,0,1,1])==1),
    np.argwhere(np.array([0,0,1,1])==1).flatten()
)

[[2]
 [3]]
[2 3]


## Suprise

In [127]:
def surprise(p):
    if p==0:
        return "Undefined"
    return np.log2(1/p)
    
printAll(
    surprise(0),
    surprise(0.1),
    surprise(0.5),
    surprise(0.9),
    surprise(1)
)

Undefined
3.321928094887362
1.0
0.15200309344505006
0.0


## Entropy

In [146]:
def entropy(ps):
    return -np.sum([p * np.log2(p) for p in ps if p>0])

printAll(
    entropy([0.5,0.5]),
    entropy([0.9,0.1]),
    entropy([0.99,0.01]),
    entropy([1, 0]),
)

1.0
0.4689955935892812
0.08079313589591118
-0.0


In [147]:
def entropy_(y):
    hist = np.bincount(y)
    ps = hist/len(y)
    return entropy(ps)

entropy_([1,1,1,0])

0.8112781244591328

## Information Gain

IG = E(P) - [Weighted Avg] . E(Children)

In [198]:
X = np.array([1,1,0,0,1,1,0])
y = np.array([0,0,1,1,1,0,0])

parent_entropy = entropy_(y)

l_idxs = np.argwhere(X==0).flatten()
r_idxs = np.argwhere(X==1).flatten()

n, n_l, n_r = len(y), len(l_idxs), len(r_idxs)

l_y, r_y = y[l_idxs], y[r_idxs]

e_l, e_r = entropy_(l_y), entropy_(r_y)

child_entropy = (n_l/n) * e_l + (n_r/n) * e_r

parent_entropy - child_entropy

0.12808527889139443

In [142]:
class DecisionTree:
    def __init__(self):
        pass
    
    def fit(self, X, y):
        self.n_features = X.shape[1]
        self._grow_tree(X, y)
        
    def predict(self, X):
        pass
        
    def _grow_tree(self, X, y):
        n_samples, n_feats = X.shape # 670, 10
        n_labels = len(np.unique(y)) # 2

        # Stopping Criteria
        
        print(self.n_features)

In [143]:
model = DecisionTree()
model.fit(X_train, y_train)
model.predict(X_test)

10
